apiVersion: apps/v1
kind: Deployment
metadata:
  name: rainforest-api
  labels:
    app: rainforest-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rainforest-api
  template:
    metadata:
      labels:
        app: rainforest-api
    spec:
      containers:
      - name: rainforest-api
        image: dariolignana96/rainforest-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
